version: "3.7"
services:
  db:
    image: postgres:12-alpine
    restart: on-failure:3
    networks:
      - internal
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis
    restart: on-failure:3
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - internal

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure:3
    depends_on:
      - db
      - redis
    networks:
      - internal
    command: >
      bash -c "alembic upgrade head && uvicorn --reload --host 0.0.0.0 --port 8000 --log-level info bsl.main:app"

  huey:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    env_file:
      - .env
    command: >
      bash -c "huey_consumer.py bsl.main.huey"
    depends_on:
      - redis
      - db
      - backend
    networks:
      - internal

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure:3
    depends_on:
      - backend
    networks:
      - internal


volumes:
  app-db-data:

networks:
  internal:
    driver: bridge


